const bienvenue = [
  "Welkom",
  "Mirë se vini",
  "Willkommen",
  "Herzlich",
  "willkommen",
  "Welkomma",
  "Marhaban",
  "Ahlan",
  "Bari galoust",
  "Xos gelmissiniz",
  "Welkum",
  "Ongi etorri",
  "Swagata",
  "Ansuf yiswen",
  "Yisek",
  "scyra zaprasajem",
  "Kyo tzo pa eit",
  "Ani kié",
  "Dobro dosli",
  "Degemer mad",
  "Dagemer mat",
  "Dobre doshul",
  "Benvinguts",
  "Ulihebisdi",
  "Huan yíng",
  "Huan yíng guang lín",
  "Karibu",
  "Eoso eoseyo",
  "Bonavinuta",
  "Bel bonjou",
  "Bienvini",
  "Ben vini",
  "Bienvéni",
  "Bienvini",
  "Bienvéni",
  "Dobrodosli",
  "Dobro dosli",
  "Velkommen",
  "Bienvenido",
  "Bienvenida",
  "Bienvenidos",
  "Bonvenon",
  "Tere tulemast",
  "Gabitê",
  "Vælkomin",
  "Tervetuloa",
  "Welkom",
  "Wìllkòmme",
  "Binvignut",
  "Fàilte",
  "Fáilte",
  "Benvido",
  "Croeso",
  "Planvenguda",
  "Mikouabô",
  "Kalos irthate",
  "Eguahé porá",
  "Baroukh habaim",
  "Swaagat",
  "Aap ka swaagat hein",
  "üdvözlöm",
  "Selamat datang",
  "Velkomin",
  "Benvenuto",
  "Benvenuta",
  "Benvenuti",
  "Yôkoso",
  "Irasshaimase",
  "Séyiz l’beinv’nu",
  "Séyiz les beinv’nus",
  "Amrehva ysswèn",
  "L’aalama",
  "Som svakoum",
  "Drumbaca",
  "Nodé",
  "Bi xer hati",
  "Benvenguda",
  "Gnindi ton hap",
  "Laipni ludzam",
  "Boyeyi bolamu",
  "Sveiki atvyke",
  "Wëllkom",
  "Dobredojde",
  "Selamat datang",
  "Swagatham",
  "Tonga soa",
  "Merhba",
  "Haere mai",
  "Miawezon",
  "Tavtai morilogtun",
  "Ne y waoongo",
  "Welkom",
  "Namaste",
  "Velkommen",
  "Benvenguts",
  "Khush amdeed",
  "Ji aayien nu",
  "Saasriyakaal",
  "Bon bini",
  "Khosh âmadid",
  "Khoshumadi",
  "Witaj",
  "Witajcie",
  "Witamy",
  "Bem-vindo",
  "Benvenguda",
  "Bine ai venit",
  "Bine ati venit",
  "Dobro pojalovat",
  "Afio mai",
  "Susu mai ma",
  "maliu mai",
  "Benènnidu",
  "Beni benìu",
  "Dobrodosli",
  "Wauya",
  "Mauya",
  "Bhali karay aaya",
  "Vitame vás",
  "Vitajte",
  "Dobrodosel",
  "Dobrodosla",
  "Dobrodosli",
  "Zupinje z te videtite",
  "Välkommen",
  "Härzliche wöikomme",
  "Karibu",
  "Karibuni",
  "Tuloy ka",
  "Tuloy po kayo",
  "Maeva",
  "Manava",
  "Nalvaravu",
  "Rahim itegez",
  "Vítejte",
  "Swagatham",
  "Yindii ton rap",
  "Hosgeldiniz",
  "Gazhasa oetiskom",
  "Laskavo prosymo",
  "Xin chào",
  "Chào",
  "Hoan nghênh",
  "Bénvnou",
  "Bénvnowe",
  "Wilicome",
  "Diarama",
  "Wilkum",
  "ékouabô",
  "ékabô",
  "sawubona",
  "uwamkelekile"
]; // lenght 152


export default bienvenue; 













